language: node_js
node_js:
  - '4'
sudo: false
install: 
    - "npm install"
    - "npm install babel-polyfill@6.23.0"
script:
    - "npm run cover"
after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov
env:
    global:
    - CODECOV_TOKEN: "36c8d4e5-f8d4-4433-8e7b-482961b85248"