language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
sudo: false
install: 
    - "npm install"
script:
    - "npm run cover"
after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov